from open_manim_slides.base import Slide
from open_manim_slides.convert import convert_to_html
from open_manim_slides.layout import assert_no_overlap, assert_reasonably_centered, assert_within_safe_frame
from open_manim_slides.theme import (
    COLOR_ACCENT,
    COLOR_ACCENT_2,
    COLOR_BACKGROUND,
    COLOR_MUTED,
    COLOR_TEXT,
    FONT_SIZE_BODY,
    FONT_SIZE_CAPTION,
    FONT_SIZE_HEADING,
    FONT_SIZE_TITLE,
    SPACING_LG,
    SPACING_MD,
    SPACING_SM,
    SPACING_XL,
    SPACING_XS,
    diagram_with_caption,
    heading,
    title_slide,
    two_column,
)

__all__ = [
    "COLOR_ACCENT",
    "COLOR_ACCENT_2",
    "COLOR_BACKGROUND",
    "COLOR_MUTED",
    "COLOR_TEXT",
    "FONT_SIZE_BODY",
    "FONT_SIZE_CAPTION",
    "FONT_SIZE_HEADING",
    "FONT_SIZE_TITLE",
    "SPACING_LG",
    "SPACING_MD",
    "SPACING_SM",
    "SPACING_XL",
    "SPACING_XS",
    "Slide",
    "assert_no_overlap",
    "assert_reasonably_centered",
    "assert_within_safe_frame",
    "convert_to_html",
    "diagram_with_caption",
    "heading",
    "title_slide",
    "two_column",
]
